// Test script to verify endpoints when server is running
console.log("🔧 Endpoint Testing Script");
console.log("========================");
console.log("");
console.log("This script helps you test your backend endpoints.");
console.log("Make sure your server is running before executing tests.");
console.log("");
console.log("To start your server, run:");
console.log("  node openaitomanychat.js");
console.log("");
console.log("Then test endpoints with these commands:");
console.log("");
console.log("1. Health Check:");
console.log("   PowerShell: Invoke-RestMethod -Uri \"http://localhost:3000/health\" -UseBasicParsing");
console.log("   cURL: curl http://localhost:3000/health");
console.log("");
console.log("2. Webhook Endpoint:");
console.log("   PowerShell: Invoke-RestMethod -Uri \"http://localhost:3000/make/webhook\" -Method POST -ContentType \"application/json\" -Body '{\"message\": \"Test\", \"userId\": \"user123\"}'");
console.log("   cURL: curl -X POST http://localhost:3000/make/webhook -H \"Content-Type: application/json\" -d \"{\\\"message\\\": \\\"Test\\\", \\\"userId\\\": \\\"user123\\\"}\"");
console.log("");
console.log("3. Public Schedule:");
console.log("   PowerShell: Invoke-RestMethod -Uri \"http://localhost:3000/schedule/public?date_from=2025-10-16\" -UseBasicParsing");
console.log("   cURL: curl \"http://localhost:3000/schedule/public?date_from=2025-10-16\"");
console.log("");
console.log("⚠️  Note: Accessing http://localhost:3000/ directly will return a 404 error");
console.log("   because there is no root route defined in your application.");
console.log("");
console.log("✅ Your application is designed as an API backend service with specific endpoints.");
console.log("   Always use the correct endpoint URLs for testing.");